export const SET_USER = 'SET_USER';

export const ADD_LOCAL_STREAM = 'ADD_LOCAL_STREAM';
export const REMOVE_LOCAL_STREAM = 'REMOVE_LOCAL_STREAM';
export const TOGGLE_MIC = 'TOGGLE_MIC';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const MICROPHONE = 'MICROPHONE';
export const SPEAKER = 'SPEAKER';
export const CAMERA = 'CAMERA';
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME';
export const SET_LOCAL_USER_ID = 'SET_USER_ID';
export const SET_TOKENS = 'SET_TOKENS';
export const SET_CHAT_CLIENT_REF = 'SET_CHAT_CLIENT_REF';

export const ADD_REMOTE_STREAM = 'ADD_REMOTE_STREAM';
export const REMOVE_REMOTE_STREAM = 'REMOVE_REMOTE_STREAM';
export const TOGGLE_IS_REMOTE_VIDEO_AVAILABLE = 'TOGGLE_IS_REMOTE_VIDEO_AVAILABLE';
export const SET_REMOTE_USER_NAME = 'SET_REMOTE_USER_NAME';
export const SET_REMOTE_USER_ID = 'SET_REMOTE_USER_ID';

export const TAB_PARTICIPANT = 'TAB_PARTICIPANT';
export const TAB_CHAT = 'TAB_CHAT';
export const TAB_SETTINGS = 'TAB_SETTINGS';
export const TOGGLE_TAB_HOME = 'TOGGLE_TAB_HOME';
export const TAB_HOME = 'TAB_HOME';
export const TAB_AUTH = 'TAB_AUTH';

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const RESET_PARTICIPANT = 'RESET_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';

export const ADD_MICROPHONE_DEVICES = 'ADD_MICROPHONE_DEVICES';
export const ADD_SPEAKER_DEVICES = 'ADD_SPEAKER_DEVICES';
export const SET_MICROPHONE = 'SET_CAMERA';
export const SET_SPEAKER = 'SET_SPEAKER';
export const SET_DEVICES = 'SET_DEVICES';
export const UPDATE_AUDIO_DEVICES = 'UPDATE_AUDIO_DEVICES';

export const SET_THREAD_ID = 'SET_THREAD_ID';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_FRONT = 'ADD_MESSAGE_FRONT';
export const SET_MESSAGE_HISTORY = 'SET_MESSAGE_HISTORY';
export const SET_THREAD_PARTICIPANTS = 'SET_THREAD_PARTICIPANTS';
export const ADD_THREAD_PARTICIPANT = 'ADD_THREAD_PARTICIPANT';
export const RESET_THREAD = 'RESET_THREAD';

export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const RESET_SELECTED_USER = 'RESET_SELECTED_USER';
