export const SET_USER = 'SET_USER';

export const ADD_LOCAL_STREAM = 'ADD_LOCAL_STREAM';
export const REMOVE_LOCAL_STREAM = 'REMOVE_LOCAL_STREAM';
export const TOGGLE_MIC = 'TOGGLE_MIC';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const MICROPHONE = 'MICROPHONE';
export const SPEAKER = 'SPEAKER';
export const CAMERA = 'CAMERA';
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME';

export const ADD_REMOTE_STREAM = 'ADD_REMOTE_STREAM';
export const REMOVE_REMOTE_STREAM = 'REMOVE_REMOTE_STREAM';
export const TOGGLE_IS_REMOTE_VIDEO_AVAILABLE = 'TOGGLE_IS_REMOTE_VIDEO_AVAILABLE';
export const SET_REMOTE_USER_NAME = 'SET_REMOTE_USER_NAME';

export const TAB_PARTICIPANT = 'TAB_PARTICIPANT';
export const TAB_CHAT = 'TAB_CHAT';
export const TAB_SETTINGS = 'TAB_SETTINGS';

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
